name: CI

on: push

env:
  node_version: ${{ vars.NODE_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: npm

      - run: npm ci

      # Check whether Prettier has errors.
      - run: npm run check:prettier

      # Check whether build is successful.
      - run: npm run build
