name: Merge develop → main

on: workflow_dispatch

env:
  gh_pat: ${{ secrets.GH_PAT }}

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.gh_pat }}

      # Merge using the --ff-only flag to ensure that only fast-forward commits
      # are allowed.
      - name: Merge develop into main
        run: |
          git fetch
          git checkout main
          git merge --ff-only develop
          git push origin main
