name: Pre-release

on:
  push:
    branches: ['main']

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic release
        uses: glazerdesktop/actions/semantic-release@main
        with:
          is_prerelease: true
          repository_url: 'github.com:glazerdesktop/glazewm-js.git'
          gh_publish: true
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          npm_publish: true
          npm_token: ${{ secrets.NPM_TOKEN }}
