name: Synchronize `main`

on: workflow_dispatch

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GH_PAT }}

      # Merge using the --ff-only flag to ensure that only fast-forward commits
      # are allowed.
      - name: Merge develop into main
        run: |
          git checkout main
          git merge --ff-only develop
          git push origin main
