name: Validate PR title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          npm install -D @commitlint/config-conventional@17.7 @commitlint/cli@17.7

          # Configure commitlint to use conventional config.
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

          echo $PR_TITLE | npx commitlint --verbose
